base_url = "https://sajadzarei.ir"

compile_sass = false

build_search_index = false


taxonomies = [
    {name = "type", feed = false}
  ]

[markdown.highlighting]
theme = "github-dark"
render_emoji = true
